config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  resources :users, only: [:show, :edit, :update] do
    collection do
      get "bookmark_list"
    end
  end
  resources :articles do
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create]
    collection do
      get "confirm"
      get "search"
    end
  end
  resources :relationships, only: [:create,  :destroy]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :article

  validates_uniqueness_of :article_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_article

  def create
    favorite = current_user.favorites.build(article_id: params[:article_id])
    favorite.save
  end

  def destroy
    favorite = Favorite.find_by(article_id: params[:article_id], user_id: current_user.id)
    favorite.destroy
  end

  private

  def set_article
    @article = Article.find(params[:article_id])
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% if article.liked_by?(current_user) %>
    <p><%= link_to "マネしたいリストから削除", article_favorites_path(article.id), method: :delete, remote: true, class: :delete_fav%></p>
  <% else %>
    <p><%= link_to "マネしたい！", article_favorites_path(article.id), method: :post, remote: true, class: :save_fav%></p>
  <% end %>
<% end %>
<p class="count_favorite"><%= article.favorites.count%><span>Fav</span></p>

app/views/favorites/create.js.erb
$("#likes_buttons_<%= @article.id %>").html("<%= j(render partial: "favorites/favorite", locals: {article: @article}) %>");

app/views/favorites/destroy.js.erb
$("#likes_buttons_<%= @article.id %>").html("<%= j(render partial: "favorites/favorite", locals: {article: @article}) %>");