config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  resources :users, only: [:show, :edit, :update] do
    collection do
      get "bookmark_list"
    end
  end
  resources :articles do
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create]
    collection do
      get "confirm"
      get "search"
    end
  end
  resources :relationships, only: [:create,  :destroy]
end

app/models/article.rb
class Article < ApplicationRecord
  enum status: { draft: 0, published: 1 }

  belongs_to :user
  has_one_attached :image
  has_many :article_tag_relations, dependent: :destroy
  has_many :tags, through: :article_tag_relations
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  def liked_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.create_article_ranking
    Article.find(Favorite.group(:article_id).order('count(article_id) desc').limit(5).pluck(:article_id))
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :confirm]
  before_action :set_article, only: [:edit, :update, :destroy, :show]
  before_action :draft_prohibited, only: :show
  before_action :move_to_index, only: [:edit, :destroy]
  before_action :set_q, only: [:index, :search]

  def index
    @articles = Article.published.order(created_at: :desc).includes(:user)
    @rank_articles = Article.create_article_ranking
  end

  def new
    @form = ArticleTag.new
  end

  def create
    @form = ArticleTag.new(article_params)
    @form.save ? (redirect_to @form, notice: '投稿が完了しました！') : (render :new)
  end

  def edit
    @form = ArticleTag.new(article: @article)
  end

  def update
    @form = ArticleTag.new(article_params, article: @article)
    if @form.save
      if @article.published?
        redirect_to article_path(@article), notice: '投稿の更新が完了しました！'
      else
        redirect_to root_path, notice: '記事を下書きに戻しました。'
      end
    else
      render :edit
    end
  end

  def destroy
    redirect_to root_path, notice: '削除が完了しました。' if @article.destroy
  end

  def show
    @review = Review.new
    @reviews = @article.reviews.includes(:user).order(created_at: :desc)
  end

  def search
    @results = @q.result.order(created_at: :desc)
  end

  def confirm
    @articles = current_user.articles.draft.order(created_at: :desc).includes(:user)
  end

  private

  def article_params
    params.require(:article).permit(:title, :detail, :how_brew, :why_brew, :commit, :taste, :image,
                                    :name, :status).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def draft_prohibited
    redirect_to root_path unless @article.published?
  end

  def move_to_index
    redirect_to root_path unless user_signed_in? && current_user.id == @article.user.id
  end

  def set_q
    @q = Article.published.ransack(params[:q])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
    <div class="card">
      <% if article.image.attached? %>   
        <%= link_to image_tag(article.image.variant(resize:"400x400"), class: :card__img), article_path(article), method: :get %>   
      <% end %>
      <div class="card__body">
        <%= link_to article.title, article_path(article), class: :card__title%>        
        <% article.tags.each do |tag|%>
          <p class="card__summary">
            <%= safe_join(tag.name.split("\n"), tag(:br)) %>
          </p>
        <% end %>
        <%= link_to "by #{article.user.nickname}", user_path(article.user.id), class: :card__user %>    
      </div>
    </div>

app/views/articles/_form.html.erb
<div class="post">
   <%= form_with model: form, local: true do |f|%>

      <%= render "devise/shared/error_messages", model: form%>

      <div class="field">
      <%= f.label :title, "レシピのタイトル（必須）" %><br />
      <%= f.text_area :title%>
      </div>

      <div class="field">
      <%= f.label :image, "投稿したい画像があればここをクリックしてください" %><br />
      <%= f.file_field :image%>
      </div>

      <div class="field">
      <%= f.label :detail, "コーヒーの詳細（必須）" %><br />
      <%= f.text_area :detail%>
      </div>

      <div class="field">
      <%= f.label :how_brew, "淹れ方の詳細(必須）" %><br />
      <%= f.text_area :how_brew%>
      </div>

      <div class="field">
      <%= f.label :why_brew, "なぜそうしたのか（参考にした記事など）（必須）" %><br />
      <%= f.text_area :why_brew %>
      </div>

      <div class="field">
      <%= f.label :commit, "こだわりポイント" %><br />
      <%= f.text_area :commit%>
      </div>

      <div class="field">
      <%= f.label :taste, "お味はいかがでしたか？（必須）" %><br />
      <%= f.text_area :taste%>
      </div>

      <div class="field">
      <%= f.label :name, "タグ (必須)"%><br />
      <%= f.text_area :name%>
      </div>

      <%= f.select :status, Article.statuses.keys.map{|k| [t("enums.articles.status.#{k}"), k]}%> 

      <div class="action">
      <%= f.submit "投稿する", class: :form__btn %>
      </div>

   <% end %>

   <strong ><%= link_to "トップページにもどる", root_path, class: "btn root_link"%></strong>
</div>

app/views/articles/confirm.html.erb
<%= render "devise/shared/global_header"%>
<%= render "devise/shared/second_half_header"%>
<div class="draft_wrapper">
  <% @articles.each do |article| %>
    <ul class="draft">
      <li class="draft_title"><%= article.title %></li>
      <li><%= link_to "更新する", edit_article_path(article), class:"update"%></li>
    </ul>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render "devise/shared/global_header"%>
<% breadcrumb :edit_article, @article%> 
<%= breadcrumbs separator: " &rsaquo; " %>
<%= render "form", form: @form %> 

app/views/articles/index.html.erb
<%= render "devise/shared/global_header"%>
<%= render "devise/shared/second_header"%>
<%= render "devise/shared/done_flash_message"%>
<div class="index_body">
  <div class="card__wrapper">
    <%= render partial: "article", collection: @articles %>
  </div>
  <div class="rank">
    <h2>真似したいランキング</h2>
    <div class="rank_box">  
      <% @rank_articles.each.with_index(1) do |article, i|%>
        <div class="rank_title">
          <%= i %>位 <%= link_to article.title, article_path(article), class: "title_name"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<%= render "devise/shared/global_header"%>
<%= render "form", form: @form %> 

app/views/articles/search.html.erb
  <%= render "devise/shared/global_header"%>
  <%= render "devise/shared/second_header"%>
  <%= render "devise/shared/done_flash_message"%>
  <% if @results.blank? %>
    <p>Sorry...<br />検索結果に当てはまる記事は見つかりませんでした</p>
  <% end %>
  <div class="card__wrapper">
    <%= render partial: "article", collection: @results %>
  </div>

app/views/articles/show.html.erb
<%= render "devise/shared/global_header"%>
<%= render "devise/shared/second_half_header"%> 
<% breadcrumb :article, @article%>
<%= breadcrumbs separator: " &rsaquo; " %>
<%= render "devise/shared/done_flash_message"%>

<div class="article">
  <%# ここから記事情報 %>
  <div class="article_info">
    <div class="upper_head">
      <div class="upper_head_left ">
        <p class="title">
          <%= @article.title%>
        </p>
        <p class="nickname">
          by<%= link_to @article.user.nickname, user_path(@article.user.id), class: :nickname_ho%>
        </p>
      </div>
      <% if user_signed_in? && current_user.id == @article.user.id%>
        <div class="upper_head_right">
          <%= link_to "編集", edit_article_path(@article), class: :edit_button%>
          <%= link_to "削除", article_path(@article), method: :delete, class: :destroy_button, data: {confirm: "削除しますか？"} %>
        </div>
      <% end %>
    </div>
    <% if @article.image.attached?%>
      <div class="middle_head">
        <%= image_tag @article.image.variant(resize: "400x400"), class: :image%>
      </div>
    <% end %>
    <div class="lower_head">
      <p class="details">
        コーヒーの詳細
      </p>
      <%= safe_join(@article.detail.split("\n"), tag(:br))%>
    </div>
    <div class="upper_body">
      <div class="how_brew">
        <p class="details">
          どうやって作ったか
        </p>
        <%= safe_join(@article.how_brew.split("\n"), tag(:br))%>
      </div>
      <div class="why_brew">
        <p class="details">
          なぜそうしたか
        </p>
        <%= text_url_to_link(h(safe_join(@article.why_brew.split("\n"), tag(:br)))).html_safe%>
      </div>
    </div>
    <div class="middle_body">
      <p class="details">
          お味は？
      </p>
      <%= safe_join(@article.taste.split("\n"), tag(:br))%>
    </div>
    <div class="lower_body">
       <p class="details">
          こだわりポイント
      </p>
      <%= safe_join(@article.commit.split("\n"), tag(:br))%>
    </div>
    <div class="lower__body">
       <p class="details">
          タグ
      </p>
      <% @article.tags.each do |tag|%>
        <%= safe_join(tag.name.split("\n"), tag(:br))%>
      <% end %>
    </div>
    <div class="foot">
      <div id="likes_buttons_<%= @article.id %>">
        <%= render partial: "favorites/favorite", locals: {article: @article}%>
      </div>
    </div>
  </div>      
  <%# //ここまで、記事情報 %>
  <%# ここからコメント情報 %>
  <div class="comment_info">
    <p class="details">レビュー欄</p>
    <% if user_signed_in?%>
      <%= form_with model: [@article, @review], class: :comment_input do |f|%>
        <%= f.text_field :review, class: :input_form%>
        <%= f.submit "レビューを投稿する"%>
      <% end %>
    <% else %>
      <p><%= link_to "ログインする", new_user_session_path, class: :log_in%>とレビューを投稿できるようになります！</p>
    <% end %>
    <div class="comment_index">
      <% @reviews.each do |review|%>
        <div class="comment">
          <%= link_to review.user.nickname, user_path(review.user.id), class: :comment_by%><br />
          <%= safe_join(review.review.split("\n"), tag(:br)) %>
        </div>
      <% end %>
    </div>
  </div>
  <%# //ここまでコメント情報 %>
</div>