config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'articles#index'
  resources :users, only: [:show, :edit, :update] do
    collection do
      get "bookmark_list"
    end
  end
  resources :articles do
    resource :favorites, only: [:create, :destroy]
    resources :reviews, only: [:create]
    collection do
      get "confirm"
      get "search"
    end
  end
  resources :relationships, only: [:create,  :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles
  has_many :favorites, dependent: :destroy
  has_many :favorite_articles, through: :favorites, source: :article
  has_many :reviews, dependent: :destroy
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "follow_id"
  has_many :followers, through: :reverse_of_relationships, source: :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :drink_coffee
  belongs_to :job

  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  # freezeメソッドで、オブジェクトの値変化を不可能に(破壊的メソッドへの対策)
  validates_format_of :password, with: PASSWORD_REGEX, message: 'には英字と数字の両方を含めてください', on: :create
  validates :job_id, :drink_coffee_id, numericality: { other_than: 1, message: 'を選択してください' }
  validates :nickname, presence: true

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to current_user
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    @user_articles = @user.articles.published.order(created_at: :desc)
  end

  def bookmark_list
    @favorite_articles = current_user.favorite_articles.order('favorites.created_at desc')
  end

  private

  def user_params
    params.require(:user).permit(:email, :nickname, :job_id, :drink_coffee_id, :favorite_shop)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/bookmark_list.html.erb
<%= render "devise/shared/global_header"%>
<%= render "devise/shared/second_half_header"%> 
<%= render "devise/shared/done_flash_message"%>

<div class="card__wrapper">
  <% if @favorite_articles.blank? %>
    <p>マネしたいリストに投稿してみよう！</p>
  <% else %>
    <%= render partial: "articles/article", collection: @favorite_articles %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render "devise/shared/global_header"%>
<% breadcrumb :edit_user, current_user%>
<%= breadcrumbs separator: " &rsaquo; " %>

<div class="devise">
  <h2 class="devise_title">ユーザー情報の更新</h2>

  <%= form_with model: current_user, class: :devise_form, local: true do |f| %>

    <%= render "devise/shared/error_messages", model: current_user %> 

    <div class="field">
      <%= f.label :email%><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>

    <div class="check_box box">
      <%= f.label :job_id%><br />
      <%= f.collection_select(:job_id, Job.all, :id, :name, {}) %>
    </div>

    <div class="field">
      <%= f.label :nickname%><br />
      <%= f.text_area :nickname, maxlength: "40", placeholder: "例) コーヒーマン"%>
    </div>

    <div class="check_box box extra_margin">
      <%= f.label :drink_coffee_id %><br />
      <%= f.collection_select(:drink_coffee_id, DrinkCoffee.all, :id, :name, {}) %>
    </div>

    <div class="field">
      <%= f.label :favorite_shop, "お気に入りのお店"%><br />
      <%= f.text_area :favorite_shop, placeholder: "例) 〇〇珈琲店, 〇〇coffee" %>
    </div>

    <div class="actions">
      <%= f.submit "登録する" %>
    </div>
  <% end %>
  <strong ><%= link_to "トップページにもどる", root_path, class: "btn root_link"%></strong>
</div>

app/views/users/show.html.erb
<%= render "devise/shared/global_header"%>
<%= render "devise/shared/second_half_header"%> 
<% breadcrumb :user, @user%>
<%= breadcrumbs separator: " &rsaquo; " %>

<div class="users">
  <div class="user">
    <h2 class="user_name"><%= "#{@user.nickname}のページ" %></h2>
     <%if @user.id == current_user.id%>
      <div class="edit_box">
        <%= link_to "編集する", " :id/edit", class: :edit_button%>
      </div>
      <% else %>
        <%= render "relationships/follow_button", user: @user %>
    <% end %>
  </div>
  <div class="user_info">
    <p class="info_box">職業<br /></p>
    <div class="user_detail">
      <%= @user.job.name%>
    </div>
    <p class="info_box">1日にコーヒーを飲む量<br /></p>
    <div class="user_detail">
      <%= "1日にコーヒーを#{@user.drink_coffee.name}飲みます"%>
    </div>
    <p class="info_box">お気に入りのお店<br /></p>
    <div class="user_detail">
      <%= "#{@user.favorite_shop}"%><br />
    </div>
  </div>
</div>
<%# ここまで、ユーザー詳細情報の表示 %>
<%# ここから、投稿した記事一覧表示 %>
<div class="card__wrapper">
  <% @user_articles.each do |article|%>
    <div class="card">
        <% if article.image.attached? %>   
          <%= link_to image_tag(article.image.variant(resize:"400x400"), class: :card__img), article_path(article), method: :get %>
        <% end %>
        <div class="card__body">
          <%= link_to article.title, article_path(article), class: :card__title%>         
          <% article.tags.each do |tag|%>
            <p class="card__summary">
              <%= safe_join(tag.name.split("\n"), tag(:br))%>
            </p>
          <% end %>
        </div>
    </div>
  <% end %>
</div>